### Get JWT for BDP
#GET localhost:2000/jwt?user=achrist&password=achrist
#Accept: application/json

#### GRAB JWT
POST http://localhost:2000/jwt
Content-Type: application/json

{
  "username": "achrist",
  "password": "achrist"
}

#### GRAB JWT with user in params
POST http://localhost:2000/jwt?username=achrist&password=achrist






